ALTER TABLE Customers AUTO_INCREMENT = 1;
ALTER TABLE BankAccounts AUTO_INCREMENT = 1;
ALTER TABLE Transactions AUTO_INCREMENT = 1;
ALTER TABLE Employees AUTO_INCREMENT = 1;
ALTER TABLE Branches AUTO_INCREMENT = 1;
ALTER TABLE Loans AUTO_INCREMENT = 1;
ALTER TABLE CreditCards AUTO_INCREMENT = 1;
ALTER TABLE Payments AUTO_INCREMENT = 1;
